baseURL: https://qi-ren-0125.netlify.app
languageCode: en-us
title: Portfolio Website for Qi REN
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    #subtitle: |-
    #  #A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
    #  #AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, my name is Qi Ren. This is a Portfolio Website I am building for myself
  blog: {}
  contact:
    address:
      - city: London, Singapore, Shenzhen
        country: UK, Singapore, China
        #street: street
        title: Where I'm based
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: qi.ren.13@gmail.com
        title: Email
    enable: yes
    #phone:
    #  - phone: (000) 000-0000 x1234
    #    title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Qi Ren 2023
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://www.twitter.com
      #- icon: fa-facebook
      #  label: Facebook
      #  url: https://www.facebook.com
      #- icon: fa-instagram
      #  label: Instagram
      #  url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/1817
      #- icon: fa-linkedin
      #  label: LinkedIn
      #  url: https://www.linkedin.com
  image: ''
  name: Qi Ren
  navigation:
    #button1:
     # - name: Get Started
      #  url: projects
    #button2:
     # - name: Log In
      #  url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blog
        url: blogs
      - name: Projects
        url: projects
      #- name: Elements
      #  url: elements.html
    menu: Menu
    #subtitle: By HTML5 Up
    title: Home
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: My first project
        title: ML with IMDB Data
        url: projects/ml_imdb_1
      - image: pic02.jpg
        subtitle: My second project
        title: Finding best Model for Credit Card Fraud Data
        url: projects/fraud_1
    #  - image: pic03.jpg
     #   subtitle: This is project 3
      #  title: Project 3
       # url: blogs/project_3
    #  - image: pic04.jpg
     #   subtitle: This is project 4
      #  title: Project 4
       # url: blogs/project_4
    #  - image: pic05.jpg
     #   subtitle: This is project 5
      #  title: Project 5
       # url: blogs/project_5
    #  - image: pic06.jpg
     #   subtitle: This is Project 6
      #  title: Project 6
       # url: blogs/project_6
  two:
    buttonText: Time to Rock n Roll
    enable: yes
    subtitle: "I am currently an MBA student at London Business School
      \n    I am interested in how data is changing the way we perceive the political and business world \n    Sometimes I write about geopolitics, sometimes I code. \n    This site is created as part of my course work with Kostis Christodoulou.\n    Get in touch with through the social media links at the bottom!"
    title: About myself
    url: blogs
