baseURL: https://qi-ren-0125.netlify.app
languageCode: en-us
title: Portfolio Website for Qi REN
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      #A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
      #AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, my name is Qi Ren. This is a Portfolio Website I am building for myself
  blog: {}
  contact:
    address:
      - city: London, Singapore, Shenzhen
        country: UK, Singapore, China
        #street: street
        title: Where I'm based
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: qi.ren.13@gmail.com
        title: Email
    enable: yes
    #phone:
    #  - phone: (000) 000-0000 x1234
    #    title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Qi Ren 2023
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://www.twitter.com
      #- icon: fa-facebook
      #  label: Facebook
      #  url: https://www.facebook.com
      #- icon: fa-instagram
      #  label: Instagram
      #  url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/1817
      #- icon: fa-linkedin
      #  label: LinkedIn
      #  url: https://www.linkedin.com
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Projects
        url: projects
      #- name: Elements
      #  url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: This is to showcase my first project
        title: ML with IMDB Data
        url: blogs/ml_imdb_1
      - image: pic02.jpg
        subtitle: This is project 2
        title: Project 2
        url: blogs/project_2
      - image: pic03.jpg
        subtitle: This is project 3
        title: Project 3
        url: blogs/project_3
      - image: pic04.jpg
        subtitle: This is project 4
        title: Project 4
        url: blogs/project_4
      - image: pic05.jpg
        subtitle: This is project 5
        title: Project 5
        url: blogs/project_5
      - image: pic06.jpg
        subtitle: This is Project 6
        title: Project 6
        url: blogs/project_6
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "some words here
      \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: A Title
    url: blogs
